server.port=8189
spring.application.name=iam-service

jwt.secret=${JWT_SECRET}
jwt.expiration=103600000

spring.datasource.url=jdbc:postgresql://postgres:5432/post_hub
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.default_schema=v1_iam_service
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.schemas=v1_iam_service

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=iam_service

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs