spring.application.name=iam_service
server.servlet.context-path=/

server.port=8189

jwt.secret=akgbskbYpxNe6F9gT+J86YgQP5TIdiufRrewDunIIx4dfYTamoRazdkG8gTLWzKMUSpDRSXELEtGuEXALJS/hA==
  jwt.expiration=103600000


spring.datasource.url=jdbc:postgresql://localhost:5432/post_hub_local
spring.datasource.username=postgres
spring.datasource.password=123qwe
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=v1_iam_service
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=v1_iam_service

end.points.posts=/posts
end.points.id=/{id}
end.points.create=/create
end.points.all=/all
end.points.search=/search
end.points.users=/users
end.points.auth=/auth
end.points.login=/login
end.points.refresh.token=/refresh/token
end.points.register=/register
end.points.comments=/comments

swagger.servers.first=http://localhost:8189
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.com.post_hub.iam_service=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG