server.port=8189
server.servlet.context-path=/
spring.application.name=iam_service

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=103600000

# Database (ScaleGrid)
spring.datasource.url=jdbc:postgresql://SG-post-hub-db-7727-pgsql-master.servers.mongodirector.com:5432/postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.properties.hibernate.default_schema=v1_iam_service
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.schemas=v1_iam_service
spring.flyway.locations=classpath:db/migration

# Kafka
kafka.enabled=true
spring.kafka.bootstrap-servers=kafka:9092

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG

# IAM service Endpoints
end.points.id=/{id}
end.points.users=/users
end.points.posts=/posts
end.points.comments=/comments
end.points.create=/create
end.points.auth=/auth
end.points.login=/login
end.points.refresh.token=/refresh/token
end.points.register=/register
end.points.search=/search

# Swagger
swagger.servers.first=http://${SERVER_IP}:8100
swagger.servers.second=http://${SERVER_IP}:8189
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Actuator for health-check
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Consul
spring.cloud.consul.enabled=false
spring.cloud.consul.discovery.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false